### ISSUE TITLE
Bug#1 Consicutive teams without bed got added to the same team in Solos making them a Team of 2 Finals.

### ISSUE THREAD

**Issue by Eradiator** [Tofpu/bedwars-swap-addon#2]
_*Screenshots*_
![SalwyrrLauncher 21-06-2022 13 30 42](https://user-images.githubusercontent.com/100428401/174750328-00e09a97-dbdf-4af4-bf2a-78ce573cd57b.png)
![SalwyrrLauncher 20-06-2022 21 08 49](https://user-images.githubusercontent.com/100428401/174750395-d5c71b32-57b5-45f6-91f7-5358ffac22aa.png)
![SalwyrrLauncher 20-06-2022 21 08 53](https://user-images.githubusercontent.com/100428401/174750408-e6369e1f-faf8-484f-b235-eb5d6c1650cc.png)
![SalwyrrLauncher 21-06-2022 13 30 36](https://user-images.githubusercontent.com/100428401/174750420-a74442cc-9342-43f2-b7b5-d7f9b525220e.png)
![SalwyrrLauncher 21-06-2022 13 30 37](https://user-images.githubusercontent.com/100428401/174750438-a3765c2b-c831-4ad0-8daf-084fc3ac3788.png)
![SalwyrrLauncher 21-06-2022 13 30 41](https://user-images.githubusercontent.com/100428401/174750446-785c7c7d-bb3d-4bc0-9dc6-b988a5d3777d.png)

_I was able to reproduce it_
*Hope onto a swap game*
*Solos*
*Break bed of two teams next to each other*

_*What was supposed to happen*_
Bed-less teams swaps with each other rather than swapping  into other bed-less team

_Debug_
 https://pastebin.com/rvtBcHFr  (I guess line 2044 shows the debug)

**Comment by Eradiator** [comment]
idk if this happens in Doubles or 3v3v3v3 or 4v4v4v4 too

**Comment by Eradiator** [comment]
after a small period of testing with 4v4v4v4 to reproduce the same bug.
I was able to find the same bug in 4v4v4v4 also
Not only that (The bedless team got swapped into me)
**_SCREENSHOT_**
![SalwyrrLauncher 21-06-2022 14 51 15](https://user-images.githubusercontent.com/100428401/174768655-5c8eb019-4fb3-4610-8d75-73e405ed3b16.png)
Here is the Debug LOG
https://pastebin.com/Nug0849S

**Comment by Eradiator** [comment]
Line 355- GREEN DIDNT GET SWAPPED SO BLUE MERGED WITH GREEN

**Comment by Tofpu** [comment]
This bug, among many others, has been successfully addressed since the official [release of 1.1.1](https://github.com/Tofpu/bedwars-swap-addon/releases/tag/1.1.1). 

Thank you for your detailed report!
