### ISSUE TITLE
The Starting team is show in the game-end-top-chat

### ISSUE THREAD

**Issue by Eradiator** [Tofpu/bedwars-swap-addon#5]
**SCREENSHOTS**
▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃
![2022-06-22_13 01 15](https://user-images.githubusercontent.com/100428401/174971389-bf3aff90-50f2-4b10-8c37-4b5614ed25c6.png)

1. The winner is shown as Bot-19 (pink at starting)
2. I was pink team at the end(while victory)
▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃
![2022-06-22_12 50 06](https://user-images.githubusercontent.com/100428401/174971354-9f9f2559-72e7-45e9-875c-74bd798988ed.png)

1. Tab showing the teams at the  starting of the game.
▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃
**FIX REQUIRED**
Show the person who won instead of the person in that team at the starting.
▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃
**ADDITIONAL SERVER SOFTWARE INFO**
Using Paper 1.12.2
Linux Mint 20.03
Version 1.0.2
▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃
**HOW TO REPRODUCE THIS BUG**
 1- Join a game
 2- Kill everybody
 3- See the game-end-top-chat
 4- you see the bug
▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃

**Comment by Eradiator** [comment]
Hope this helps ;)

**Comment by Tofpu** [comment]
The jar below might possibly solve the issue at hand here. I do not feel like opening an instance of Minecraft at the moment, so if any of you could possibly reply back with the results would be awesome.

https://github.com/Tofpu/bedwars-swap-addon/suites/7067331171/artifacts/278818652

**Comment by Eradiator** [comment]
Thx
